service:
  name: recipe-book-graphql
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  profile: recipe-book

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
